site_name: Intel ROS2 Project Tutorial
site_author: Liu Shenghui
pages:
- Home: index.md
- Preparation: preparation.md
- Installation: installation.md
- Quick Start: package_instruction.md
- Acknowledgement: acknowledegment.md
theme: readthedocs
